version: '3.8'

services:
  simple-form:
    image: simple-form:latest
    ports:
      - "9010:8000"
    environment:
      LOG_PASSWORDS: "false"
      LOG_DIR: /app/logs
    volumes:
      - /var/log/simple-form:/app/logs
    networks:
      - npm_net
    deploy:
      restart_policy:
        condition: any
      replicas: 1

networks:
  npm_net:
    external: true
